export const projects = [
  {
    id: 1,
    title: "Kurorin Dashboard",
    category: "Dashboard Design",
    description: "A futuristic data analytics dashboard with real-time metrics, cinematic charts, and glassmorphism UI components.",
    stack: ["React", "TypeScript", "Tailwind", "GSAP"],
    image: "/projects/project1.webp",
    liveUrl: "#",
    githubUrl: "#",
    color: "#b100ff",
    animStyle: "tilt",
  },
  {
    id: 2,
    title: "E-Commerce Platform",
    category: "Web Design",
    description: "A premium e-commerce experience with immersive product showcases, 3D previews, and smooth micro-interactions.",
    stack: ["Next.js", "Stripe", "Three.js", "Framer Motion"],
    image: "/projects/project2.webp",
    liveUrl: "#",
    githubUrl: "#",
    color: "#00d0ff",
    animStyle: "float",
  },
  {
    id: 3,
    title: "Portfolio Website",
    category: "Frontend Development",
    description: "Award-winning interactive portfolio with scroll-driven storytelling, WebGL canvas animations, and cinematic UI.",
    stack: ["Next.js", "R3F", "GSAP", "Framer Motion"],
    image: "/projects/project3.webp",
    liveUrl: "#",
    githubUrl: "#",
    color: "#8b5cf6",
    animStyle: "scale",
  },
  {
    id: 4,
    title: "SaaS Landing Page",
    category: "UI/UX Design",
    description: "A conversion-optimized SaaS landing page with dynamic hero, animated feature cards, and glassmorphism pricing tables.",
    stack: ["Next.js", "Tailwind", "GSAP", "Lenis"],
    image: "/projects/project4.webp",
    liveUrl: "#",
    githubUrl: "#",
    color: "#ff0080",
    animStyle: "slide",
  },
]
